# Frontend build:
#   * counter (WASM) — GHC 9.12 via ghc-wasm-meta
#   * auth    (WASM) — GHC 9.12 via ghc-wasm-meta
#
# Single-toolchain: both targets compile to wasm32-wasi using the same
# `wasm32-wasi-cabal` invocation. The `auth` executable talks to Supabase
# through a small JS shim (`frontend/js/supabase-ffi.js`) that the
# native-WASM `foreign import javascript` calls into.

{ inputs, root, ... }:
{
  perSystem = { self', pkgs, lib, ... }:
    let
      ghcWasm = inputs.ghc-wasm-meta.packages.${pkgs.system}.all_9_12;

      frontendWasm = pkgs.stdenvNoCC.mkDerivation {
        name = "hcentner-blog-wasm";
        src = builtins.path {
          path = ../../../frontend;
          name = "hcentner-blog-frontend-src";
          filter = _path: _type: true;
        };

        nativeBuildInputs = [
          ghcWasm
          pkgs.nodejs
          pkgs.cacert
          pkgs.git
        ];

        # Fixed-output derivation: network access allowed, output hash pinned.
        # Rebuild with `lib.fakeHash` to get the new hash when deps change.
        outputHashMode = "recursive";
        outputHashAlgo = "sha256";
        outputHash = "sha256-Fx53cCM5OWmApqhtykxyaJtHxEAod/2FUUEjLP1XI04=";

        buildPhase = ''
          export HOME=$TMPDIR
          export SSL_CERT_FILE=${pkgs.cacert}/etc/ssl/certs/ca-bundle.crt

          wasm32-wasi-cabal update
          wasm32-wasi-cabal build counter auth --allow-newer

          GHC_LIBDIR=$(wasm32-wasi-ghc --print-libdir)
          mkdir -p $out

          for target in counter auth; do
            WASM_BIN=$(wasm32-wasi-cabal list-bin "$target")
            "$GHC_LIBDIR/post-link.mjs" \
              -i "$WASM_BIN" \
              -o "$out/''${target}_ghc_wasm_jsffi.js"
            cp "$WASM_BIN" "$out/''${target}.wasm"

            if command -v wasm-opt &>/dev/null; then
              wasm-opt -Oz "$out/''${target}.wasm" -o "$out/''${target}.wasm"
            fi
          done

          # Copy the JS shim used by the `auth` executable's
          # `foreign import javascript` declarations.
          cp $src/js/supabase-ffi.js $out/supabase-ffi.js
        '';

        dontInstall = true;
        dontFixup = true;
      };

      siteContent = lib.fileset.toSource {
        inherit root;
        fileset = lib.fileset.unions [
          (root + /static/posts)
          (root + /static/templates)
          # css/default.css is generated by the Hakyll rule from Design.Css,
          # not copied from static/css (which now holds no tracked files).
          (root + /static/images)
          (root + /static/js)
          (root + /static/about)
          (root + /static/about.html)
          (root + /static/index.html)
          (root + /static/CNAME)
          (root + /static/favicon.ico)
          (root + /static/robots.txt)
        ];
      };
    in
    {
      packages.wasm = frontendWasm;

      packages.site = pkgs.stdenvNoCC.mkDerivation {
        name = "hcentner-blog-site";
        src = siteContent;

        nativeBuildInputs = [
          self'.packages.hcentner-blog
          pkgs.glibcLocales
        ];

        LANG = "en_US.UTF-8";
        LOCALE_ARCHIVE = "${pkgs.glibcLocales}/lib/locale/locale-archive";

        buildPhase = ''
          cd static

          # Copy WASM + JS artifacts into place before Hakyll build
          mkdir -p wasm
          cp ${frontendWasm}/counter.wasm wasm/
          cp ${frontendWasm}/counter_ghc_wasm_jsffi.js wasm/
          cp ${frontendWasm}/auth.wasm wasm/
          cp ${frontendWasm}/auth_ghc_wasm_jsffi.js wasm/
          cp ${frontendWasm}/supabase-ffi.js wasm/

          site build

          mv _site $out
        '';

        dontInstall = true;
        dontFixup = true;
      };

      # Validates the generated site's internal links with Hakyll's `check`
      # command. Consumes the built `packages.site` output, so `nix flake check`
      # builds the site first and then link-checks it. Internal links only:
      # the Nix sandbox has no network for external link checks.
      checks.site-links = pkgs.runCommand "hcentner-blog-site-links"
        {
          nativeBuildInputs = [
            self'.packages.hcentner-blog
            pkgs.glibcLocales
          ];
          LANG = "en_US.UTF-8";
          LOCALE_ARCHIVE = "${pkgs.glibcLocales}/lib/locale/locale-archive";
        } ''
        cp -r ${self'.packages.site} _site
        site check --internal-links
        touch $out
      '';

      devShells.wasm = pkgs.mkShell {
        name = "hcentner-blog-wasm";
        meta.description = "WASM frontend development environment";
        packages = [
          ghcWasm
          pkgs.nodejs
        ];
      };
    };
}
