cabal-version:      2.4
name:               hcentner-blog
version:            0.1.0.0
license:            MIT
copyright:          2025 Harrison Centner
maintainer:         hcentner@umich.edu
author:             Harrison Centner
category:           Web
synopsis:           A blog mostly about software, built with Hakyll
extra-source-files:

common shared
  ghc-options:
    -Wall -Wincomplete-record-updates -Wincomplete-uni-patterns
    -Wmissing-deriving-strategies -Wunused-foralls -Wunused-foralls
    -fprint-explicit-foralls -fprint-explicit-kinds

  default-extensions:
    DataKinds
    DerivingStrategies
    DerivingVia
    LambdaCase
    MultiWayIf
    NoStarIsType
    OverloadedStrings
    StrictData
    TypeFamilies
    ViewPatterns

  build-depends:
    , aeson
    , async
    , base
    , clay
    , data-default
    , directory
    , filepath
    , hakyll
    , lucid
    , mtl
    , optics-core
    , pandoc
    , pandoc-types
    , relude
    , text
    , time

  default-language:   GHC2021

library
  import:          shared
  hs-source-dirs:  src
  exposed-modules:
    Design.Css
    Design.Email
    Design.Tokens

executable site
  import:         shared
  hs-source-dirs: app
  main-is:        site.hs
  build-depends:  hcentner-blog

executable emails
  import:         shared
  hs-source-dirs: app
  main-is:        emails.hs
  build-depends:
    , bytestring
    , hcentner-blog

test-suite email-tests
  import:         shared
  type:           exitcode-stdio-1.0
  hs-source-dirs: test
  main-is:        EmailSpec.hs
  build-depends:
    , hcentner-blog
    , tasty
    , tasty-hunit
